# This file was *autogenerated* from the file lab.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_12 = Integer(12)
__tmp__=var("x,y"); f = symbolic_expression(_sage_const_2 *x**_sage_const_2  + _sage_const_3 *x**_sage_const_4  + _sage_const_4 *x*y**_sage_const_2  + _sage_const_12 *x**_sage_const_2 *y**_sage_const_3  + y**_sage_const_4  + _sage_const_6 *y**_sage_const_6 ).function(x,y)
dfdx = diff(f, x)
dfdy = diff(f, y)
d2fdx2 = diff(f, x, _sage_const_2 )
d2fdy2 = diff(f, y, _sage_const_2 )
d2fdxdy = diff(dfdx, y)
print d2fdxdy

print(solve([dfdx == _sage_const_0 , dfdy == _sage_const_0 ], x, y))
